image: gradle:8.10.2-jdk11

stages:
  - build
  - publish
  - release

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  NEXUS_URL: "${NEXUS_URL}"
  VERSION_PROPERTIES_FILE: "version.properties"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - echo "VERSION=${CI_COMMIT_REF_NAME}" >> version.properties

build:
  stage: build
  script:
    - gradle assemble --build-cache
  artifacts:
    paths:
      - build/outputs/aar/*.aar

publish:
  stage: publish
  script:
    - gradle publish --info
  only:
    - master
    - tags

release:
  stage: release
  script:
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git checkout master
    - ./gradlew incrementVersion --info
    - git add version.properties
    - git commit -m "Increment version to $(grep 'version=' $VERSION_PROPERTIES_FILE | cut -d'=' -f2)"
    - git push origin master
  only:
    - tags
  when: on_success
