name: Android Library CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Get actual version
        id: get_actual_version
        run: |
          echo "VERSION=$(grep version zsi/version.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload AAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: aar-file
          path: zsi/build/outputs/aar/zsi-${{ env.VERSION }}.aar

  publish:
    permissions:
      contents: write
    environment: Hardware
    env:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_URL: ${{ secrets.NEXUS_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Download AAR artifact
        uses: actions/download-artifact@v3
        with:
          name: aar-file
          path: zsi/build/outputs/aar/

      - name: Get actual version
        id: get_actual_version
        run: |
          echo "VERSION=$(grep version zsi/version.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: ${{ secrets.NEXUS_URL }}
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASSWORD }}
          format: maven2
          repository: maven-releases
          coordinates: groupId=nordix.dev artifactId=zsi version=${{ env.VERSION }}
          assets: extension=aar
          filename: zsi/build/outputs/aar/zsi-${{ env.VERSION }}.aar

      - name: Create Git tag
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: "New release of ZSI."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .aar file to GitHub release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: zsi/build/outputs/aar/zsi-${{ env.VERSION }}.aar
          asset_name: zsi-${{ env.VERSION }}.aar
          asset_content_type: application/octet-stream

  finalize:
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Increment version and commit
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          ./gradlew incrementVersion
          git add .
          git commit -m "Increment version"
          git push
